name: deploy_backend

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/deploy_backend.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "scoutly"
          heroku_email: "jkao97@yahoo.com"
          appdir: "backend"
